#!/bin/sh

# Send the header so that i3bar knows we want to use JSON:
echo '{ "version": 1 }'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:
exec conky -c $HOME/.i3/conkyrc-i3bar
#exec conky -c $HOME/.i3/conkyrc
#exec conky -c /home/anton/program/opensource/i3wm-config/conky/conky.conf
